server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VivekChaurasia03/microservice-config-server.git
          clone-on-start: true